name: Test Credentials

on: []
  # workflow_dispatch:

permissions:
  contents: write

jobs:
  test-creds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests python-dotenv pytz selenium webdriver-manager

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Test token refresh
        env:
          DISPLAY: :99
          RESIDEO_CONSUMER_KEY: ${{ secrets.RESIDEO_CONSUMER_KEY }}
          RESIDEO_CONSUMER_SECRET: ${{ secrets.RESIDEO_CONSUMER_SECRET }}
          HONEYWELL_USERNAME: ${{ secrets.HONEYWELL_USERNAME }}
          HONEYWELL_PASSWORD: ${{ secrets.HONEYWELL_PASSWORD }}
          HONEYWELL_TOTP_SECRET: ${{ secrets.HONEYWELL_TOTP_SECRET }}
          HONEYWELL_ACCESS_TOKEN: ${{ secrets.HONEYWELL_ACCESS_TOKEN }}
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3

          echo "Testing credential refresh..."
          python automated_token_refresh.py --test

      - name: Commit test logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add thermostat_log.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Test credential refresh $(date '+%m/%d/%y %H:%M:%S')"
          git push