name: Thermostat Check

on:
  schedule:
    - cron: '45 1,2,3,4,5,6,7,8,9,10,11 * * *'  # 9:45pm-6:45am ET every 25 min (converted to UTC)
    - cron: '10,35 2,3,4,5,6,7,8,9,10,11,12 * * *'  # :10 and :35 minutes past hours
  workflow_dispatch:

jobs:
  check-thermostat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - name: Run thermostat check
        env:
          HONEYWELL_ACCESS_TOKEN: ${{ secrets.HONEYWELL_ACCESS_TOKEN }}
          RESIDEO_CONSUMER_KEY: ${{ secrets.RESIDEO_CONSUMER_KEY }}
        run: python thermostat_control.py
      - run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add thermostat_log.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update thermostat log"
          git push