name: Thermostat Check

on:
  schedule:
    - cron: '15,45 1,2,3,4,5,6,7,8 * * *'  # 9:45pm-5:30am ET every 30 min (EDT/UTC-4)
    # Note: During EST (winter), use: '15,45 2,3,4,5,6,7,8,9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-thermostat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt

      - name: Try thermostat control
        id: thermostat
        env:
          HONEYWELL_ACCESS_TOKEN: ${{ secrets.HONEYWELL_ACCESS_TOKEN }}
          RESIDEO_CONSUMER_KEY: ${{ secrets.RESIDEO_CONSUMER_KEY }}
        run: |
          if python thermostat_control.py; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Setup Chrome and ChromeDriver (if token refresh needed)
        if: steps.thermostat.outputs.success == 'false'
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true

      - name: Install additional dependencies for token refresh
        if: steps.thermostat.outputs.success == 'false'
        run: pip install selenium webdriver-manager

      - name: Setup environment for token refresh
        if: steps.thermostat.outputs.success == 'false'
        run: echo "Token refresh needed"

      - name: Run token refresh and retry thermostat
        if: steps.thermostat.outputs.success == 'false'
        env:
          DISPLAY: :99
          RESIDEO_CONSUMER_KEY: ${{ secrets.RESIDEO_CONSUMER_KEY }}
          RESIDEO_CONSUMER_SECRET: ${{ secrets.RESIDEO_CONSUMER_SECRET }}
          HONEYWELL_USERNAME: ${{ secrets.HONEYWELL_USERNAME }}
          HONEYWELL_PASSWORD: ${{ secrets.HONEYWELL_PASSWORD }}
          HONEYWELL_TOTP_SECRET: ${{ secrets.HONEYWELL_TOTP_SECRET }}
          HONEYWELL_ACCESS_TOKEN: ${{ secrets.HONEYWELL_ACCESS_TOKEN }}
        run: |
          # Start virtual display for headless browser
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3

          # Run automated token refresh and retry thermostat control
          python run_with_refresh.py

      - name: Commit logs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add thermostat_log.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update thermostat log $(date '+%m/%d/%y %H:%M:%S')

          🤖 Generated with [Claude Code](https://claude.ai/code)

          Co-Authored-By: Claude <noreply@anthropic.com>"
          git push